# Numpy Assignment

In [3]:
import numpy as np

np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

## Numpyy arry with elements [15,25,35,45,55]

In [ ]:

np.array([15,25,35,45,55])

array([15, 25, 35, 45, 55])

## Creat array 2D with value [[20,40,60],[80,100,150]] 

In [ ]:

np.array([[20,40,60],[80,100,150]])

array([[ 20,  40,  60],
       [ 80, 100, 150]])

## Creat array 2D with values [[10,20,30],[40,50,60]]

In [ ]:

np.array( [[10,20,30],[40,50,60]])

array([[10, 20, 30],
       [40, 50, 60]])

## Add 5 to [1,2,3,4,5]

In [13]:
np.array([[1,2,3,4,5]]) + 5

array([[ 6,  7,  8,  9, 10]])

7. ## Add 10 to [10,20,30,40].

In [14]:
np.array([10,20,30,40])+10

array([20, 30, 40, 50])

In [15]:
# Add -3 to [3,6,9,12].
np.array([3,6,9,12])-3

array([0, 3, 6, 9])

In [16]:
# Add 100 to [0,50,100].
np.array([0,50,100])+100

array([100, 150, 200])

In [17]:
# Add 2 to [0.5,1.5,2.5].
np.array([0.5,1.5,2.5])+2

array([2.5, 3.5, 4.5])

In [18]:
# Add 7 to [10,15,20,25,30].
np.array([10,15,20,25,30])+7

array([17, 22, 27, 32, 37])

In [19]:
# Add 1 to all elements of [100,200,300].
np.array([100,200,300])+1

array([101, 201, 301])

In [20]:

# Add 50 to [5,10,15,20].
np.array([5,10,15,20])

array([ 5, 10, 15, 20])

In [21]:
# 13. Add 0.25 to [0.25,0.5,0.75].
np.array([0.25,0.5,0.75]) + 0.25

array([0.5 , 0.75, 1.  ])

In [22]:
# 14. Subtract 2 from [5,10,15].
np.array([5,10,15])

array([ 5, 10, 15])

In [23]:
# 15. Subtract 10 from [20,30,40].
np.array([20,30,40])

array([20, 30, 40])

In [24]:
# Subtract 1 from [1,2,3,4,5].
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
# 17. Subtract 100 from [200,300,400].
np.array([200,300,400])

array([200, 300, 400])

In [26]:
# 18. Subtract 0.5 from [1.5,2.5,3.5].
np.array([1.5,2.5,3.5])

array([1.5, 2.5, 3.5])

In [27]:
# 19. Subtract 5 from [50,100,150].
np.array([50,100,150])

array([ 50, 100, 150])

In [28]:
# 20. Subtract 7 from [10,20,30,40].
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [29]:
# 21. Subtract 25 from [25,50,75].
np.array([25,50,75])

array([25, 50, 75])

In [30]:
# 21. Subtract 25 from [25,50,75].
np.array([25,50,75])

array([25, 50, 75])

In [31]:
# 22. Subtract 0.1 from [0.1,0.2,0.3].
np.array([0.1,0.2,0.3])

array([0.1, 0.2, 0.3])

In [32]:
# 23. Multiply [1,2,3,4,5] by 2.
np.array([1,2,3,4,5])/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [33]:
# 24. Multiply [10,20,30] by 5.
np.array([10,20,30])/5

array([2., 4., 6.])

In [34]:
# 25. Multiply [0.5,1.5,2.5] by 4.
np.array([0.5,1.5,2.5])/4

array([0.125, 0.375, 0.625])

In [35]:
# 26. Multiply [100,200,300] by 10.
np.array([100,200,300])*3

array([300, 600, 900])

In [36]:
# 27. Multiply [2,4,6,8] by 0.5.
np.array([2,4,6,8])/0.5

array([ 4.,  8., 12., 16.])

In [37]:
# 28. Multiply [7,14,21] by 3.
np.array([7,14,21])*3

array([21, 42, 63])

In [38]:
# 29. Multiply [5,10,15,20] by -1.
np.array([5,10,15,20])*-1

array([ -5, -10, -15, -20])

In [39]:
# 30. Multiply [9,18,27] by 0.1.
np.array([9,18,27])*0.1

array([0.9, 1.8, 2.7])

In [40]:
# 31. Multiply [50,100,150] by 2.5.
np.array([50,100,150])*2.5

array([125., 250., 375.])

In [42]:
# 32. Create a zeros array of shape (2,3).
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
# 33. Create a zeros array of shape (3,2).
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
# 34. Create a ones array of shape (2,3).
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# 35. Create a ones array of shape (3,2).
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
# 36. Find min and max of [1,2,3,4,5].
print(np.min([1,2,3,4,5]))
print(np.max([1,2,3,4,5]))

1
5


In [50]:
# 37. Find mean of [10,20,30,40].
print(np.mean([10,20,30,40]))

25.0


In [51]:
# 38. Find std of [1,1,1,1,1].
print(np.std([1,1,1,1,1]))

0.0


In [53]:
# 39. Find max of [50,100,150].
print(np.max([50,100,150]))

150


In [55]:
# 40. Find min of [10,5,20,15].
print(np.min([10,5,20,15]))

5


In [57]:
# 41. Find mean of [2,4,6,8,10].
print(np.mean([2,4,6,8,10]))

6.0


In [58]:
# 42. Find std of [5,10,15,20,25].
print(np.std([5,10,15,20,25]))

7.0710678118654755


In [59]:
# 43. Find mean of [1.5,2.5,3.5,4.5].
print(np.mean([1.5,2.5,3.5,4.5]))

3.0


In [63]:
# 44. Find std of [100,200,300,400].
print(np.std([100,200,300,400]))

111.80339887498948


In [64]:
# 45. Get first element of [10,20,30,40].
print(np.std([[10,20,30,40]]))

11.180339887498949


In [71]:
# 46. Get last element of [5,10,15,20,25].
arr= np.array([5,10,15,20,25])
print(arr[-1])

25


In [72]:
# 47. Slice [0,10,20,30,40,50] from index 2 to 4.
arr=np.array([0,10,20,30,40,50])
print(arr[2:4])

[20 30]


In [76]:
# 48. Slice [1,2,3,4,5,6] to get first three elements.
arr=np.array([1,2,3,4,5,6])
print(arr[0:2])

[1 2]


In [80]:
# 49. Slice [2,4,6,8,10,12] to get 2nd element.
arr=np.array([2,4,6,8,10,12])
print(arr[2])

6


In [82]:
# 50. Get middle element of [100,200,300].
arr=np.array([100,200,300])
print(arr[1])

200


In [84]:
# 51. Slice [10,20,30,40,50] from index 1 to end.
arr=np.array([10,20,30,40,50])
print(arr[1:])

[20 30 40 50]
